const products = [
    {
     "Sl No": 1,
     "SKU": "MCPPL-DSSP-0400",
     "Short Title": "Doctor's Surgical Spirit IP 400 ML",
     "Brand Name": "Multicure Pharma",
     "Manufacturer": "Multicure Pharma Pvt Ltd",
     "Manufacturer Address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Marketer": "Multicure Pharma Pvt Ltd",
     "Marketer address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Description": "Multicure Doctor's Surgical Spirit I.P. is used as an antiseptic and disinfectant for cleaning and sanitizing wounds, cuts, and abrasions. It contains alcohol and can be used as a skin cleanser before surgery and injections.",
     "Bullet point 1": "It contains industrial methylated spirit, which has antimicrobial properties that can help to kill germs on the surface of the skin",
     "Bullet point 2": "When applied to the skin, Multicure Doctor's Surgical Spirit can help to cool and soothe the affected area",
     "Bullet point 3": "Surgical spirits can be used to clean and disinfect surfaces, including medical equipment and instruments",
     "Bullet point 4": "Surgical spirits are often included in first aid kits and can be used to clean and disinfect wounds",
     "Direction to Use": "Pour a few drops on cotton and clean the affected area",
     "Safety information": "For external use only.\nStore in a cool and dry place, away from sunlight.\nKeep out of reach of children",
     "Ingredients": "Methyl salicylate, Diethyl phthalate, Castor oil, Industrial methylated spirit",
     "OTC\/RX": "OTC",
     "Product Category": "Antiseptic Liquid",
     "Product Form": "Liquid",
     "Consume Type": "Topical",
     "Unit (s) in Pack": 1,
     "Box Content": "1 - Doctor's Surgical Spirit 400 Ml Bottle",
     "Size": "400 ML",
     "Stock Quantity": 100,
     "Pack Form\n(Bottle, Tube , Strip etc.)": "Bottle",
     "Product Weight In Grams": "400 G",
     "L in CMs": 6.5,
     "W in Cms": 6.5,
     "H in Cms": 17,
     "HSN": 30049099,
     "GST %": 12,
     "MRP": 230,
     "SP": 207,
     "Discount %": 10,
     "Images Link": "https:\/\/drive.google.com\/drive\/folders\/1W9kl97e7WQ3VF6wZxz7LiGtdZ1B7KPu2?usp=drive_link",
     "productImages": [
        "https://ree-route.s3.ap-south-1.amazonaws.com/1706890207662.png", 
        "https://ree-route.s3.ap-south-1.amazonaws.com/1706890297704.png"
    ]
    },
    {
     "Sl No": 2,
     "SKU": "MCPPL-DSSP-0100",
     "Short Title": "Doctor's Surgical Spirit IP 100 ML",
     "Brand Name": "Multicure Pharma",
     "Manufacturer": "Multicure Pharma Pvt Ltd",
     "Manufacturer Address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Marketer": "Multicure Pharma Pvt Ltd",
     "Marketer address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Description": "Multicure Doctor's Surgical Spirit I.P. is used as an antiseptic and disinfectant for cleaning and sanitizing wounds, cuts, and abrasions. It contains alcohol and can be used as a skin cleanser before surgery and injections.",
     "Bullet point 1": "It contains industrial methylated spirit, which has antimicrobial properties that can help to kill germs on the surface of the skin",
     "Bullet point 2": "When applied to the skin, Multicure Doctor's Surgical Spirit can help to cool and soothe the affected area",
     "Bullet point 3": "Surgical spirits can be used to clean and disinfect surfaces, including medical equipment and instruments",
     "Bullet point 4": "Surgical spirits are often included in first aid kits and can be used to clean and disinfect wounds",
     "Direction to Use": "Pour a few drops on cotton and clean the affected area",
     "Safety information": "For external use only.\nStore in a cool and dry place, away from sunlight.\nKeep out of reach of children",
     "Ingredients": "Methyl salicylate, Diethyl phthalate, Castor oil, Industrial methylated spirit",
     "OTC\/RX": "OTC",
     "Product Category": "Antiseptic Liquid",
     "Product Form": "Liquid",
     "Consume Type": "Topical",
     "Unit (s) in Pack": 1,
     "Box Content": "1 - Doctor's Surgical Spirit 100 Ml Bottle",
     "Size": "100 ML",
     "Stock Quantity": 100,
     "Pack Form\n(Bottle, Tube , Strip etc.)": "Bottle",
     "Product Weight In Grams": "100 G",
     "L in CMs": 4.5,
     "W in Cms": 4.5,
     "H in Cms": 10,
     "HSN": 30049099,
     "GST %": 12,
     "MRP": 85,
     "SP": 77,
     "Discount %": 9.411764705882353,
     "Images Link": "https:\/\/drive.google.com\/drive\/folders\/1I60Mm1-cyIlS05Casfa_lr5e295umwGp?usp=drive_link",
     "productImages": [
        "https://ree-route.s3.ap-south-1.amazonaws.com/1706894391771.png",
        "https://ree-route.s3.ap-south-1.amazonaws.com/1706894556968.png",
        "https://ree-route.s3.ap-south-1.amazonaws.com/1706894733943.png" 
     ]
    },
    {
     "Sl No": 3,
     "SKU": "MCPPL-DSSP-4500",
     "Short Title": "Doctor's Surgical Spirit IP 4.5 Ltr",
     "Brand Name": "Multicure Pharma",
     "Manufacturer": "Multicure Pharma Pvt Ltd",
     "Manufacturer Address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Marketer": "Multicure Pharma Pvt Ltd",
     "Marketer address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Description": "Multicure Doctor's Surgical Spirit I.P. is used as an antiseptic and disinfectant for cleaning and sanitizing wounds, cuts, and abrasions. It contains alcohol and can be used as a skin cleanser before surgery and injections.",
     "Bullet point 1": "It contains industrial methylated spirit, which has antimicrobial properties that can help to kill germs on the surface of the skin",
     "Bullet point 2": "When applied to the skin, Multicure Doctor's Surgical Spirit can help to cool and soothe the affected area",
     "Bullet point 3": "Surgical spirits can be used to clean and disinfect surfaces, including medical equipment and instruments",
     "Bullet point 4": "Surgical spirits are often included in first aid kits and can be used to clean and disinfect wounds",
     "Direction to Use": "Pour a few drops on cotton and clean the affected area",
     "Safety information": "For external use only.\nStore in a cool and dry place, away from sunlight.\nKeep out of reach of children",
     "Ingredients": "Methyl salicylate, Diethyl phthalate, Castor oil, Industrial methylated spirit",
     "OTC\/RX": "OTC",
     "Product Category": "Antiseptic Liquid",
     "Product Form": "Liquid",
     "Consume Type": "Topical",
     "Unit (s) in Pack": 1,
     "Box Content": "1 - Doctor's Surgical Spirit 4.5 ltr can",
     "Size": "4.5 Ltr",
     "Stock Quantity": 100,
     "Pack Form\n(Bottle, Tube , Strip etc.)": "Bottle",
     "Product Weight In Grams": "500 G",
     "L in CMs": 18,
     "W in Cms": 13,
     "H in Cms": 27.5,
     "HSN": 30049099,
     "GST %": 12,
     "MRP": 1500,
     "SP": 1399,
     "Discount %": 6.7333333333333325,
     "Images Link": "https:\/\/drive.google.com\/drive\/folders\/17PS-Pa77Nv5yO02l1QZcPqRiO35SKl2K?usp=drive_link",
     "productImages": [
        "https://ree-route.s3.ap-south-1.amazonaws.com/1706894986639.png",
        "https://ree-route.s3.ap-south-1.amazonaws.com/1706895017860.png",
        "https://ree-route.s3.ap-south-1.amazonaws.com/1706895059968.png",
        "https://ree-route.s3.ap-south-1.amazonaws.com/1706895099372.png",
        "https://ree-route.s3.ap-south-1.amazonaws.com/1706895148123.png",
     ]
    },
    {
     "Sl No": 4,
     "SKU": "MHOPC-RGLYN-0575",
     "Short Title": "Multimeds Healthcare Rose glycerin 500+75g free with pump",
     "Brand Name": "Multimeds Healthcare",
     "Manufacturer": "Multicure Pharma Pvt Ltd",
     "Manufacturer Address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Marketer": "Multimeds Healthcare (OPC) Pvt Ltd",
     "Marketer address": "LEVEL 14, 24, Concorde Tower, Vittal Mallya Road, UB City, Bengaluru, 560001",
     "Description": "Our Rose glycerine has several skincare properties because of its moisturizing power. It is an all-purpose component in beauty products, including skin and hair care to treat areas suffering from itchiness and dryness. Applying Rose glycerine to your skin may gradually improve its smoothness and suppleness",
     "Bullet point 1": "Its skin-nourishing properties, our organic glycerine can be used every day. Its regular use will help to keep your skin healthy, soft, and fresh to keep away problems associated with dryness. This hair moisture glycerine absorbs moisture from the environment which can help improve hair dryness. Safe for all skin and hair types",
     "Bullet point 2": "Cleanser and Toner: It gently cleanses and tones the skin, maintaining a balanced complexion",
     "Bullet point 3": "It can be used to alleviate chapped\/dry lips",
     "Bullet point 4": "Useful in eliminating dandruff and deals with dry, flaky scalp",
     "Bullet point 5": "It helps in strengthening the hair leading to less formation of split ends",
     "Direction to Use": "Pour a few drops of glycerin and apply it on your face, allow it to settle on the face for 20-30 minutes before washing it",
     "Safety information": "Store in a cool and dry place, away from sunlight.\nKeep out of reach of children",
     "Ingredients": "Glycerin",
     "OTC\/RX": "OTC",
     "Product Category": "Skin Moisturizer",
     "Product Form": "Liquid",
     "Consume Type": "Topical",
     "Unit (s) in Pack": 1,
     "Box Content": "1 - 575 Grams Rose Glycerin\n1 - Pump",
     "Size": "575 Grams",
     "Scent\/Flavour": "Rose",
     "Stock Quantity": 100,
     "Pack Form\n(Bottle, Tube , Strip etc.)": "Bottle",
     "Product Weight In Grams": "575 G",
     "L in CMs": 5.5,
     "W in Cms": 8.5,
     "H in Cms": 19,
     "HSN": 30049099,
     "GST %": 12,
     "MRP": 590,
     "SP": 499,
     "Discount %": 15.423728813559324,
     "Images Link": "https:\/\/drive.google.com\/drive\/folders\/17PS-Pa77Nv5yO02l1QZcPqRiO35SKl2K?usp=drive_link",
     "productImages": [
        "https://ree-route.s3.ap-south-1.amazonaws.com/1706895628765.png",
        "https://ree-route.s3.ap-south-1.amazonaws.com/1706895709984.png",
        "https://ree-route.s3.ap-south-1.amazonaws.com/1706895751365.png",
        "https://ree-route.s3.ap-south-1.amazonaws.com/1706895791558.png",
        "https://ree-route.s3.ap-south-1.amazonaws.com/1706895854644.png",
        ]
    },
    {
     "Sl No": 5,
     "SKU": "MHOPC-RGLYN-0100",
     "Short Title": "Multimeds Healthcare Rose glycerin 100 Grams",
     "Brand Name": "Multimeds Healthcare",
     "Manufacturer": "Multicure Pharma Pvt Ltd",
     "Manufacturer Address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Marketer": "Multimeds Healthcare (OPC) Pvt Ltd",
     "Marketer address": "LEVEL 14, 24, Concorde Tower, Vittal Mallya Road, UB City, Bengaluru, 560001",
     "Description": "Our Rose glycerine has several skincare properties because of its moisturizing power. It is an all-purpose component in beauty products, including skin and hair care to treat areas suffering from itchiness and dryness. Applying Rose glycerine to your skin may gradually improve its smoothness and suppleness",
     "Bullet point 1": "Its skin-nourishing properties, our organic glycerine can be used every day. Its regular use will help to keep your skin healthy, soft, and fresh to keep away problems associated with dryness. This hair moisture glycerine absorbs moisture from the environment which can help improve hair dryness. Safe for all skin and hair types",
     "Bullet point 2": "Cleanser and Toner: It gently cleanses and tones the skin, maintaining a balanced complexion",
     "Bullet point 3": "It can be used to alleviate chapped\/dry lips",
     "Bullet point 4": "Useful in eliminating dandruff and deals with dry, flaky scalp",
     "Bullet point 5": "It helps in strengthening the hair leading to less formation of split ends",
     "Direction to Use": "Pour a few drops of glycerin and apply it on your face, allow it to settle on the face for 20-30 minutes before washing it",
     "Safety information": "Store in a cool and dry place, away from sunlight.\nKeep out of reach of children",
     "Ingredients": "Glycerin",
     "OTC\/RX": "OTC",
     "Product Category": "Skin Moisturizer",
     "Product Form": "Liquid",
     "Consume Type": "Topical",
     "Unit (s) in Pack": 1,
     "Box Content": "1 - 100 Grams Rose Glycerin",
     "Size": "100 Grams",
     "Scent\/Flavour": "Rose",
     "Stock Quantity": 100,
     "Pack Form\n(Bottle, Tube , Strip etc.)": "Bottle",
     "Product Weight In Grams": "100 G",
     "L in CMs": 3.5,
     "W in Cms": 5,
     "H in Cms": 12,
     "HSN": 30049099,
     "GST %": 12,
     "MRP": 175,
     "SP": 149,
     "Discount %": 14.857142857142858,
     "Images Link": "https:\/\/drive.google.com\/drive\/folders\/1Y-88jNdqsXSs7mZs5p5I0vTpfVXgz9o_?usp=drive_link",
     "productImages": [

        ]
    },
    {
     "Sl No": 6,
     "SKU": "MCPPL-LPFN-0400",
     "Short Title": "Multicure Liquid Paraffin I.P. 400 ML",
     "Brand Name": "Multicure Pharma",
     "Manufacturer": "Multicure Pharma Pvt Ltd",
     "Manufacturer Address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Marketer": "Multicure Pharma Pvt Ltd",
     "Marketer address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Description": "liquid paraffin used as a skin moisturizer and may help to prevent dryness and scaling of the skin. When applied topically, liquid paraffin forms a protective barrier on the skin, protecting against external irritants, and helps in restoring the smoothness of the skin. Liquid paraffin is a refined mineral oil that is commonly used in cosmetics, medicine, and personal care products. It is a popular ingredient in skin care products since it coats the skin, prevents water loss, and keeps skin moisturized.",
     "Bullet point 1": "Liquid paraffin is used to moisturize the skin and may help to prevent dryness, scaling, and itching",
     "Bullet point 2": "Applying liquid paraffin to the skin can also help to protect it from damage caused by the sun, wind, and other environmental factors",
     "Bullet point 3": "Liquid paraffin may help to promote skin healing by providing a barrier that protects against further injury",
     "Bullet point 4": "Liquid paraffin comes in liquid form and can be easily applied to the skin by rubbing it in gently",
     "Safety information": "For external use only.\nStore in a cool and dry place, away from sunlight.\nKeep out of reach of children",
     "Ingredients": "Liquid Paraffin IP",
     "OTC\/RX": "OTC",
     "Product Category": "Skin Moisturizer",
     "Product Form": "Liquid",
     "Consume Type": "Topical",
     "Unit (s) in Pack": 1,
     "Size": "400 ML",
     "Scent\/Flavour": "Unscented",
     "Stock Quantity": 100,
     "Pack Form\n(Bottle, Tube , Strip etc.)": "Bottle",
     "Product Weight In Grams": "400 G",
     "L in CMs": 6.5,
     "W in Cms": 6.5,
     "H in Cms": 17,
     "HSN": 30049099,
     "GST %": 12,
     "MRP": 325,
     "SP": 275,
     "Discount %": 15.384615384615385,
     "Images Link": "https:\/\/drive.google.com\/drive\/folders\/1TlRjPe9RTN8TJm1rVwU083zisNEwvqnS?usp=drive_link"
    },
    {
     "Sl No": 7,
     "SKU": "MCPPL-LPFN-0100",
     "Short Title": "Multicure Liquid Paraffin I.P. 100 ML",
     "Brand Name": "Multicure Pharma",
     "Manufacturer": "Multicure Pharma Pvt Ltd",
     "Manufacturer Address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Marketer": "Multicure Pharma Pvt Ltd",
     "Marketer address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Description": "liquid paraffin used as a skin moisturizer and may help to prevent dryness and scaling of the skin. When applied topically, liquid paraffin forms a protective barrier on the skin, protecting against external irritants, and helps in restoring the smoothness of the skin. Liquid paraffin is a refined mineral oil that is commonly used in cosmetics, medicine, and personal care products. It is a popular ingredient in skin care products since it coats the skin, prevents water loss, and keeps skin moisturized.",
     "Bullet point 1": "Liquid paraffin is used to moisturize the skin and may help to prevent dryness, scaling, and itching",
     "Bullet point 2": "Applying liquid paraffin to the skin can also help to protect it from damage caused by the sun, wind, and other environmental factors",
     "Bullet point 3": "Liquid paraffin may help to promote skin healing by providing a barrier that protects against further injury",
     "Bullet point 4": "Liquid paraffin comes in liquid form and can be easily applied to the skin by rubbing it in gently",
     "Safety information": "For external use only.\nStore in a cool and dry place, away from sunlight.\nKeep out of reach of children",
     "Ingredients": "Liquid Paraffin IP",
     "OTC\/RX": "OTC",
     "Product Category": "Skin Moisturizer",
     "Product Form": "Liquid",
     "Consume Type": "Topical",
     "Unit (s) in Pack": 1,
     "Size": "100 ML",
     "Scent\/Flavour": "Unscented",
     "Stock Quantity": 100,
     "Pack Form\n(Bottle, Tube , Strip etc.)": "Bottle",
     "Product Weight In Grams": "100 G",
     "L in CMs": 4.5,
     "W in Cms": 4.5,
     "H in Cms": 10,
     "HSN": 30049099,
     "GST %": 12,
     "MRP": 130,
     "SP": 117,
     "Discount %": 10,
     "Images Link": "https:\/\/drive.google.com\/drive\/folders\/1TKBOyfm1qCefcANsR2geJSUc68FI7eUz?usp=drive_link"
    },
    {
     "Sl No": 8,
     "SKU": "MCPPL-GLYN-0400",
     "Short Title": "Multicure Glycerin I.P. 400 Grams",
     "Brand Name": "Multicure Pharma",
     "Manufacturer": "Multicure Pharma Pvt Ltd",
     "Manufacturer Address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Marketer": "Multicure Pharma Pvt Ltd",
     "Marketer address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Description": "Our glycerine has several skincare properties because of its moisturizing power. It is an all-purpose component in beauty products, including skin and hair care to treat areas suffering from itchiness and dryness. Applying  glycerine to your skin may gradually improve its smoothness and suppleness",
     "Bullet point 1": "Effective moisturizes the skin, makes it smooth & maintains water balance",
     "Bullet point 2": "It is great to use in the wintertime to avoid dryness of the skin",
     "Bullet point 3": "It helps to keep the skin young and reduces acne.",
     "Bullet point 4": "It can be used to alleviate chapped\/dry lips",
     "Bullet point 5": "Useful in eliminating dandruff and deals with dry, flaky scalp",
     "Direction to Use": "Pour a few drops of glycerin and apply it on your face, allow it to settle on the face for 20-30 minutes before washing it",
     "Safety information": "Store in a cool and dry place, away from sunlight.\nKeep out of reach of children",
     "Ingredients": "Glycerin",
     "OTC\/RX": "OTC",
     "Product Category": "Skin Moisturizer",
     "Product Form": "Liquid",
     "Consume Type": "Topical",
     "Unit (s) in Pack": 1,
     "Size": "400 ML",
     "Scent\/Flavour": "Unscented",
     "Stock Quantity": 100,
     "Pack Form\n(Bottle, Tube , Strip etc.)": "Bottle",
     "Product Weight In Grams": "400 G",
     "L in CMs": 6.5,
     "W in Cms": 6.5,
     "H in Cms": 17,
     "HSN": 30049099,
     "GST %": 12,
     "MRP": 350,
     "SP": 299,
     "Discount %": 14.571428571428571,
     "Images Link": "https:\/\/drive.google.com\/drive\/folders\/1REdPUxwcYjQa7DbqUZcgMexK5gEFbnNn?usp=drive_link"
    },
    {
     "Sl No": 9,
     "SKU": "MCPPL-GLYN-0100",
     "Short Title": "Multicure Glycerin I.P. 100 Grams",
     "Brand Name": "Multicure Pharma",
     "Manufacturer": "Multicure Pharma Pvt Ltd",
     "Manufacturer Address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Marketer": "Multicure Pharma Pvt Ltd",
     "Marketer address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Description": "Our glycerine has several skincare properties because of its moisturizing power. It is an all-purpose component in beauty products, including skin and hair care to treat areas suffering from itchiness and dryness. Applying  glycerine to your skin may gradually improve its smoothness and suppleness",
     "Bullet point 1": "Effective moisturizes the skin, makes it smooth & maintains water balance",
     "Bullet point 2": "It is great to use in the wintertime to avoid dryness of the skin",
     "Bullet point 3": "It helps to keep the skin young and reduces acne.",
     "Bullet point 4": "It can be used to alleviate chapped\/dry lips",
     "Bullet point 5": "Useful in eliminating dandruff and deals with dry, flaky scalp",
     "Direction to Use": "Pour a few drops of glycerin and apply it on your face, allow it to settle on the face for 20-30 minutes before washing it",
     "Safety information": "Store in a cool and dry place, away from sunlight.\nKeep out of reach of children",
     "Ingredients": "Glycerin",
     "OTC\/RX": "OTC",
     "Product Category": "Skin Moisturizer",
     "Product Form": "Liquid",
     "Consume Type": "Topical",
     "Unit (s) in Pack": 1,
     "Size": "100 ML",
     "Scent\/Flavour": "Unscented",
     "Stock Quantity": 100,
     "Pack Form\n(Bottle, Tube , Strip etc.)": "Bottle",
     "Product Weight In Grams": "100 G",
     "L in CMs": 4.5,
     "W in Cms": 4.5,
     "H in Cms": 10,
     "HSN": 30049099,
     "GST %": 12,
     "MRP": 150,
     "SP": 135,
     "Discount %": 10,
     "Images Link": "https:\/\/drive.google.com\/drive\/folders\/15Ei3bL4jFY1xYn9m4h5cVJSvA94Z1sKb?usp=drive_link"
    },
    {
     "Sl No": 10,
     "SKU": "MHOPC-LPFN-0500",
     "Short Title": "Multimeds Healthcare Liquid Paraffin 500 ML with Pump",
     "Brand Name": "Multimeds Healthcare",
     "Manufacturer": "Multicure Pharma Pvt Ltd",
     "Manufacturer Address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Marketer": "Multimeds Healthcare (OPC) Pvt Ltd",
     "Marketer address": "LEVEL 14, 24, Concorde Tower, Vittal Mallya Road, UB City, Bengaluru, 560001",
     "Description": "Multimeds liquid paraffin used as a skin moisturizer and may help to prevent dryness and scaling of the skin. When applied topically, liquid paraffin forms a protective barrier on the skin, protecting against external irritants, and helps in restoring the smoothness of the skin. Liquid paraffin is a refined mineral oil that is commonly used in cosmetics, medicine, and personal care products. It is a popular ingredient in skin care products since it coats the skin, prevents water loss, and keeps skin moisturized.",
     "Bullet point 1": "Softens the dry and hard stool",
     "Bullet point 2": "It does not clog pores. This makes it a good choice for people with acne-prone skin, as it will not cause breakouts.",
     "Bullet point 3": "Helps in treating dry skin",
     "Bullet point 4": "Provides relief in eczema and pruritus",
     "Safety information": "Store in a cool and dry place, away from sunlight.\nKeep out of reach of children",
     "Ingredients": "Liquid Paraffin",
     "OTC\/RX": "OTC",
     "Product Category": "Skin Moisturizer",
     "Product Form": "Liquid",
     "Consume Type": "Topical",
     "Unit (s) in Pack": 1,
     "Size": "500 ML",
     "Scent\/Flavour": "Unscented",
     "Stock Quantity": 100,
     "Pack Form\n(Bottle, Tube , Strip etc.)": "Bottle",
     "Product Weight In Grams": "500 G",
     "L in CMs": 5.5,
     "W in Cms": 8.5,
     "H in Cms": 19,
     "HSN": 30049099,
     "GST %": 12,
     "MRP": 500,
     "SP": 349,
     "Discount %": 30.2,
     "Images Link": "https:\/\/drive.google.com\/drive\/folders\/16Q2fpPWcW7lpIMmhG8gZ29h397toEIns?usp=drive_link"
    },
    {
     "Sl No": 11,
     "SKU": "MHOPC-LPFN-0100",
     "Short Title": "Multimeds Healthcare Liquid Paraffin 100 ML",
     "Brand Name": "Multimeds Healthcare",
     "Manufacturer": "Multicure Pharma Pvt Ltd",
     "Manufacturer Address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Marketer": "Multimeds Healthcare (OPC) Pvt Ltd",
     "Marketer address": "LEVEL 14, 24, Concorde Tower, Vittal Mallya Road, UB City, Bengaluru, 560001",
     "Description": "Multimeds liquid paraffin used as a skin moisturizer and may help to prevent dryness and scaling of the skin. When applied topically, liquid paraffin forms a protective barrier on the skin, protecting against external irritants, and helps in restoring the smoothness of the skin. Liquid paraffin is a refined mineral oil that is commonly used in cosmetics, medicine, and personal care products. It is a popular ingredient in skin care products since it coats the skin, prevents water loss, and keeps skin moisturized.",
     "Bullet point 1": "Softens the dry and hard stool",
     "Bullet point 2": "It does not clog pores. This makes it a good choice for people with acne-prone skin, as it will not cause breakouts.",
     "Bullet point 3": "Helps in treating dry skin",
     "Bullet point 4": "Provides relief in eczema and pruritus",
     "Safety information": "Store in a cool and dry place, away from sunlight.\nKeep out of reach of children",
     "Ingredients": "Liquid Paraffin",
     "OTC\/RX": "OTC",
     "Product Category": "Skin Moisturizer",
     "Product Form": "Liquid",
     "Consume Type": "Topical",
     "Unit (s) in Pack": 1,
     "Size": "100 ML",
     "Scent\/Flavour": "Unscented",
     "Stock Quantity": 100,
     "Pack Form\n(Bottle, Tube , Strip etc.)": "Bottle",
     "Product Weight In Grams": "100 G",
     "L in CMs": 3.5,
     "W in Cms": 5,
     "H in Cms": 12,
     "HSN": 30049099,
     "GST %": 12,
     "MRP": 175,
     "SP": 157,
     "Discount %": 10.285714285714285,
     "Images Link": "https:\/\/drive.google.com\/drive\/folders\/1LBwZWHZDMGNSk35hoXy1K5nZGVoBLGxq?usp=drive_link"
    },
    {
     "Sl No": 12,
     "SKU": "MCPPL-PI02-0100",
     "Short Title": "MUTADINE - Povidone Iodine 2% w\/v Gargle 100ML",
     "Brand Name": "MUTADINE",
     "Manufacturer": "Multicure Pharma Pvt Ltd",
     "Manufacturer Address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Marketer": "Multicure Pharma Pvt Ltd",
     "Marketer address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Description": "Mutadine 2% Gargle is an antiseptic and disinfectant agent that is used as a mouthwash to kill germs that cause infections of the mouth. It also relieves dryness of the mouth and sore throat.\n\nTake Mutadine 2% Gargle in the dose and duration as advised by your doctor. Make sure not to swallow the medication. Do not stop using it until you have finished the complete course, even when you feel better. You must have to avoid eating, drinking, or smoking for at least 30 minutes after using it. Do not use it for longer than your doctor has told you to and let him or her know if your condition does not improve after 2 to 4 weeks of treatment.",
     "Bullet point 1": "Treatment of Mouth infection",
     "Bullet point 2": "Treatment of Sore throat",
     "Bullet point 3": "Treatment and prevention of Oral Wound infection",
     "Bullet point 4": "Treatment of Dry mouth",
     "Direction to Use": "Pour gargle and mouthwash into the cup and dilute it with an equal amount of warm water if the taste is an issue. Swish the solution for a short time in the mouth and spit it out. Thirty-second gargle kills the germs in the mouth or throat. Repeat this every two to four hours or as directed by your dentist",
     "Size": "100 ML",
     "Scent\/Flavour": "Mint",
     "Stock Quantity": 100,
     "Pack Form\n(Bottle, Tube , Strip etc.)": "Bottle",
     "Product Weight In Grams": "100 G",
     "L in CMs": 4,
     "W in Cms": 4,
     "H in Cms": 12,
     "HSN": 30041090,
     "GST %": 12,
     "MRP": 235,
     "SP": 211,
     "Discount %": 10.212765957446807,
     "Images Link": "https:\/\/drive.google.com\/drive\/folders\/1SIv4IlFOz-JMKkSYrnnxbtzCzQEcJnQO?usp=drive_link"
    },
    {
     "Sl No": 13,
     "SKU": "MCPPL-PI05-0100",
     "Short Title": "MUTADINE - Povidone Iodine Solution 5% w\/v 100 ML",
     "Brand Name": "MUTADINE",
     "Manufacturer": "Multicure Pharma Pvt Ltd",
     "Manufacturer Address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Marketer": "Multicure Pharma Pvt Ltd",
     "Marketer address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Description": "Mutadine 5% Solution is an antiseptic and disinfectant agent. It is used for the treatment and prevention of infections in wounds and cuts. It kills the harmful microbes and controls their growth, thereby preventing infections in the affected area.\n\nMutadine 5% Solution is for external use only. You should always use it exactly as your doctor has told you. The affected area should be clean and dry before application. You must wash your hands thoroughly before and after applying this medicine. This medicine should be used regularly to get the most benefit from it. Do not use more than you need as it will not clear your condition faster and some side effects may be increased. You can help this medication work better by keeping the affected areas clean.",
     "Bullet point 1": "Used in health care as an antiseptic to prep the skin prior to medical procedures",
     "Bullet point 2": "The solution is specially formulated to combat a wide range of harmful microbes, including bacteria and viruses.",
     "Direction to Use": "Used in health care as an antiseptic to prep the skin prior to medical procedures, Let it dry for a few minutes",
     "Safety information": "Avoid contact with eyes and nose. In case of accidental contact, rinse thoroughly with water.\nDo not use it on burnt, broken or inflamed skin.",
     "Ingredients": "Povidone Iodine 5 w\/v",
     "OTC\/RX": "OTC",
     "Product Category": "Antiseptic solution",
     "Product Form": "Liquid",
     "Consume Type": "Topical",
     "Unit (s) in Pack": 1,
     "Size": "100 ML",
     "Stock Quantity": 100,
     "Pack Form\n(Bottle, Tube , Strip etc.)": "Bottle",
     "Product Weight In Grams": "100 G",
     "L in CMs": 4.5,
     "W in Cms": 4.5,
     "H in Cms": 10,
     "HSN": 30041090,
     "GST %": 12,
     "MRP": 65,
     "SP": 59,
     "Discount %": 9.230769230769232,
     "Images Link": "https:\/\/drive.google.com\/drive\/folders\/1XoN-qIOqyw3yxfJ1Uz7kPewgQ011pbLH?usp=drive_link"
    },
    {
     "Sl No": 14,
     "SKU": "MCPPL-PI05-0500",
     "Short Title": "MUTADINE - Povidone Iodine Solution 5% w\/v 500 ML",
     "Brand Name": "MUTADINE",
     "Manufacturer": "Multicure Pharma Pvt Ltd",
     "Manufacturer Address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Marketer": "Multicure Pharma Pvt Ltd",
     "Marketer address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Description": "Mutadine 5% Solution is an antiseptic and disinfectant agent. It is used for the treatment and prevention of infections in wounds and cuts. It kills the harmful microbes and controls their growth, thereby preventing infections in the affected area.\n\nMutadine 5% Solution is for external use only. You should always use it exactly as your doctor has told you. The affected area should be clean and dry before application. You must wash your hands thoroughly before and after applying this medicine. This medicine should be used regularly to get the most benefit from it. Do not use more than you need as it will not clear your condition faster and some side effects may be increased. You can help this medication work better by keeping the affected areas clean.",
     "Bullet point 1": "Used in health care as an antiseptic to prep the skin prior to medical procedures",
     "Bullet point 2": "The solution is specially formulated to combat a wide range of harmful microbes, including bacteria and viruses.",
     "Direction to Use": "Used in health care as an antiseptic to prep the skin prior to medical procedures, Let it dry for a few minutes",
     "Safety information": "Avoid contact with eyes and nose. In case of accidental contact, rinse thoroughly with water.\nDo not use it on burnt, broken or inflamed skin.",
     "Ingredients": "Povidone Iodine 5 w\/v",
     "OTC\/RX": "OTC",
     "Product Category": "Antiseptic solution",
     "Product Form": "Liquid",
     "Consume Type": "Topical",
     "Unit (s) in Pack": 1,
     "Size": "500 ML",
     "Stock Quantity": 100,
     "Pack Form\n(Bottle, Tube , Strip etc.)": "HDPE Bottle",
     "Product Weight In Grams": "500 G",
     "L in CMs": 6.5,
     "W in Cms": 6.5,
     "H in Cms": 16.5,
     "HSN": 30041090,
     "GST %": 12,
     "MRP": 275,
     "SP": 249,
     "Discount %": 9.454545454545455,
     "Images Link": "https:\/\/drive.google.com\/drive\/folders\/1v1Kcts1wFBfzT3jlsuaqIzA9UNkjZ44F?usp=drive_link"
    },
    {
     "Sl No": 15,
     "SKU": "MCPPL-PI05-2000",
     "Short Title": "MUTADINE - Povidone Iodine Solution 5% w\/v 2 Ltr",
     "Brand Name": "MUTADINE",
     "Manufacturer": "Multicure Pharma Pvt Ltd",
     "Manufacturer Address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Marketer": "Multicure Pharma Pvt Ltd",
     "Marketer address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Description": "Mutadine 5% Solution is an antiseptic and disinfectant agent. It is used for the treatment and prevention of infections in wounds and cuts. It kills the harmful microbes and controls their growth, thereby preventing infections in the affected area.\n\nMutadine 5% Solution is for external use only. You should always use it exactly as your doctor has told you. The affected area should be clean and dry before application. You must wash your hands thoroughly before and after applying this medicine. This medicine should be used regularly to get the most benefit from it. Do not use more than you need as it will not clear your condition faster and some side effects may be increased. You can help this medication work better by keeping the affected areas clean.",
     "Bullet point 1": "Used in health care as an antiseptic to prep the skin prior to medical procedures",
     "Bullet point 2": "The solution is specially formulated to combat a wide range of harmful microbes, including bacteria and viruses.",
     "Direction to Use": "Used in health care as an antiseptic to prep the skin prior to medical procedures, Let it dry for a few minutes",
     "Safety information": "Avoid contact with eyes and nose. In case of accidental contact, rinse thoroughly with water.\nDo not use it on burnt, broken or inflamed skin.",
     "Ingredients": "Povidone Iodine 5 w\/v",
     "OTC\/RX": "OTC",
     "Product Category": "Antiseptic solution",
     "Product Form": "Liquid",
     "Consume Type": "Topical",
     "Unit (s) in Pack": 1,
     "Size": "2 Ltr",
     "Stock Quantity": 100,
     "Pack Form\n(Bottle, Tube , Strip etc.)": "HDPE Can",
     "Product Weight In Grams": "2000 G",
     "L in CMs": 13,
     "W in Cms": 13,
     "H in Cms": 23,
     "HSN": 30041090,
     "GST %": 12,
     "MRP": 860,
     "SP": 777,
     "Discount %": 9.651162790697674,
     "Images Link": "https:\/\/drive.google.com\/drive\/folders\/1dv_b5fnujiEl_uS7nB3-zl31DaW34Lvj?usp=drive_link"
    },
    {
     "Sl No": 16,
     "SKU": "MCPPL-PI05-4500",
     "Short Title": "MUTADINE - Povidone Iodine Solution 5% w\/v 4.5 Ltr",
     "Brand Name": "MUTADINE",
     "Manufacturer": "Multicure Pharma Pvt Ltd",
     "Manufacturer Address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Marketer": "Multicure Pharma Pvt Ltd",
     "Marketer address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Description": "Mutadine 5% Solution is an antiseptic and disinfectant agent. It is used for the treatment and prevention of infections in wounds and cuts. It kills the harmful microbes and controls their growth, thereby preventing infections in the affected area.\n\nMutadine 5% Solution is for external use only. You should always use it exactly as your doctor has told you. The affected area should be clean and dry before application. You must wash your hands thoroughly before and after applying this medicine. This medicine should be used regularly to get the most benefit from it. Do not use more than you need as it will not clear your condition faster and some side effects may be increased. You can help this medication work better by keeping the affected areas clean.",
     "Bullet point 1": "Used in health care as an antiseptic to prep the skin prior to medical procedures",
     "Bullet point 2": "The solution is specially formulated to combat a wide range of harmful microbes, including bacteria and viruses.",
     "Direction to Use": "Used in health care as an antiseptic to prep the skin prior to medical procedures, Let it dry for a few minutes",
     "Safety information": "Avoid contact with eyes and nose. In case of accidental contact, rinse thoroughly with water.\nDo not use it on burnt, broken or inflamed skin.",
     "Ingredients": "Povidone Iodine 5 w\/v",
     "OTC\/RX": "OTC",
     "Product Category": "Antiseptic solution",
     "Product Form": "Liquid",
     "Consume Type": "Topical",
     "Unit (s) in Pack": 1,
     "Size": "4.5 Ltr",
     "Stock Quantity": 100,
     "Pack Form\n(Bottle, Tube , Strip etc.)": "HDPE Can",
     "Product Weight In Grams": "4500 G",
     "L in CMs": 18,
     "W in Cms": 13,
     "H in Cms": 27.5,
     "HSN": 30041090,
     "GST %": 12,
     "MRP": 2500,
     "SP": 2249,
     "Discount %": 10.040000000000001,
     "Images Link": "https:\/\/drive.google.com\/drive\/folders\/1cUNr4WoBbg7kg7V8_wh1IEQWO8liTo8M?usp=drive_link"
    },
    {
     "Sl No": 17,
     "SKU": "MCPPL-PI07-0100",
     "Short Title": "MUTADINE - Povidone Iodine Standardised Surgical Scrub Solution 7.5% 100 ML",
     "Brand Name": "MUTADINE",
     "Manufacturer": "Multicure Pharma Pvt Ltd",
     "Manufacturer Address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Marketer": "Multicure Pharma Pvt Ltd",
     "Marketer address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Description": "Mutadine 7.5% Solution is an antiseptic and disinfectant agent. It is used for the treatment and prevention of infections in wounds and cuts. It kills the harmful microbes and controls their growth, thereby preventing infections in the affected area.\n\nMutadine 7.5% Solution is for external use only. You should always use it exactly as your doctor has told you. The affected area should be clean and dry before application. You must wash your hands thoroughly before and after applying this medicine. This medicine should be used regularly to get the most benefit from it. Do not use more than you need as it will not clear your condition faster and some side effects may be increased. You can help this medication work better by keeping the affected areas clean.",
     "Bullet point 1": "Used in health care as an antiseptic to prep the skin prior to medical procedures, Let it dry for a few minutes",
     "Bullet point 2": "The solution is specially formulated to combat a wide range of harmful microbes, including bacteria and viruses.",
     "Direction to Use": "Used in health care as an antiseptic to prep the skin prior to medical procedures, Let it dry for a few minutes",
     "Safety information": "Avoid contact with eyes and nose. In case of accidental contact, rinse thoroughly with water.\nDo not use it on burnt, broken or inflamed skin.",
     "Ingredients": "Povidone Iodine 7.5 w\/v",
     "OTC\/RX": "OTC",
     "Product Category": "Antiseptic solution",
     "Product Form": "Liquid",
     "Consume Type": "Topical",
     "Unit (s) in Pack": 1,
     "Size": "100 ML",
     "Stock Quantity": 100,
     "Pack Form\n(Bottle, Tube , Strip etc.)": "Bottle",
     "Product Weight In Grams": "100 G",
     "L in CMs": 4.5,
     "W in Cms": 4.5,
     "H in Cms": 10,
     "HSN": 30041090,
     "GST %": 12,
     "MRP": 100,
     "SP": 90,
     "Discount %": 10,
     "Images Link": "https:\/\/drive.google.com\/drive\/folders\/1lWXOgDAE8nDQOxoQF_Wfi3nhOrmeXh7L?usp=drive_link"
    },
    {
     "Sl No": 18,
     "SKU": "MCPPL-PI07-0500",
     "Short Title": "MUTADINE - Povidone Iodine Standardised Surgical Scrub Solution 7.5% 500 ML",
     "Brand Name": "MUTADINE",
     "Manufacturer": "Multicure Pharma Pvt Ltd",
     "Manufacturer Address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Marketer": "Multicure Pharma Pvt Ltd",
     "Marketer address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Description": "Mutadine 7.5% Solution is an antiseptic and disinfectant agent. It is used for the treatment and prevention of infections in wounds and cuts. It kills the harmful microbes and controls their growth, thereby preventing infections in the affected area.\n\nMutadine 7.5% Solution is for external use only. You should always use it exactly as your doctor has told you. The affected area should be clean and dry before application. You must wash your hands thoroughly before and after applying this medicine. This medicine should be used regularly to get the most benefit from it. Do not use more than you need as it will not clear your condition faster and some side effects may be increased. You can help this medication work better by keeping the affected areas clean.",
     "Bullet point 1": "Used in health care as an antiseptic to prep the skin prior to medical procedures, Let it dry for a few minutes",
     "Bullet point 2": "The solution is specially formulated to combat a wide range of harmful microbes, including bacteria and viruses.",
     "Direction to Use": "Used in health care as an antiseptic to prep the skin prior to medical procedures, Let it dry for a few minutes",
     "Safety information": "Avoid contact with eyes and nose. In case of accidental contact, rinse thoroughly with water.\nDo not use it on burnt, broken or inflamed skin.",
     "Ingredients": "Povidone Iodine 7.5 w\/v",
     "OTC\/RX": "OTC",
     "Product Category": "Antiseptic solution",
     "Product Form": "Liquid",
     "Consume Type": "Topical",
     "Unit (s) in Pack": 1,
     "Size": "500 ML",
     "Stock Quantity": 100,
     "Pack Form\n(Bottle, Tube , Strip etc.)": "HDPE Bottle",
     "Product Weight In Grams": "500 G",
     "L in CMs": 6.5,
     "W in Cms": 6.5,
     "H in Cms": 16.5,
     "HSN": 30041090,
     "GST %": 12,
     "MRP": 450,
     "SP": 405,
     "Discount %": 10,
     "Images Link": "https:\/\/drive.google.com\/drive\/folders\/1E0DCSQm3ej9nimGG_xJ32PRDL2YKuDq2?usp=drive_link"
    },
    {
     "Sl No": 19,
     "SKU": "MCPPL-PI07-2000",
     "Short Title": "MUTADINE - Povidone Iodine Standardised Surgical Scrub Solution 7.5% 2 Ltr",
     "Brand Name": "MUTADINE",
     "Manufacturer": "Multicure Pharma Pvt Ltd",
     "Manufacturer Address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Marketer": "Multicure Pharma Pvt Ltd",
     "Marketer address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Description": "Mutadine 7.5% Solution is an antiseptic and disinfectant agent. It is used for the treatment and prevention of infections in wounds and cuts. It kills the harmful microbes and controls their growth, thereby preventing infections in the affected area.\n\nMutadine 7.5% Solution is for external use only. You should always use it exactly as your doctor has told you. The affected area should be clean and dry before application. You must wash your hands thoroughly before and after applying this medicine. This medicine should be used regularly to get the most benefit from it. Do not use more than you need as it will not clear your condition faster and some side effects may be increased. You can help this medication work better by keeping the affected areas clean.",
     "Bullet point 1": "Used in health care as an antiseptic to prep the skin prior to medical procedures, Let it dry for a few minutes",
     "Bullet point 2": "The solution is specially formulated to combat a wide range of harmful microbes, including bacteria and viruses.",
     "Direction to Use": "Used in health care as an antiseptic to prep the skin prior to medical procedures, Let it dry for a few minutes",
     "Safety information": "Avoid contact with eyes and nose. In case of accidental contact, rinse thoroughly with water.\nDo not use it on burnt, broken or inflamed skin.",
     "Ingredients": "Povidone Iodine 7.5 w\/v",
     "OTC\/RX": "OTC",
     "Product Category": "Antiseptic solution",
     "Product Form": "Liquid",
     "Consume Type": "Topical",
     "Unit (s) in Pack": 1,
     "Size": "2 Ltr",
     "Stock Quantity": 100,
     "Pack Form\n(Bottle, Tube , Strip etc.)": "HDPE Can",
     "Product Weight In Grams": "2000 G",
     "L in CMs": 13,
     "W in Cms": 13,
     "H in Cms": 23,
     "HSN": 30041090,
     "GST %": 12,
     "MRP": 1500,
     "SP": 1399,
     "Discount %": 6.7333333333333325,
     "Images Link": "https:\/\/drive.google.com\/drive\/folders\/1Z1DtBmH4V7B_QzhvCWbsZ9dmC_exU6oP?usp=drive_link"
    },
    {
     "Sl No": 20,
     "SKU": "MCPPL-PI07-4500",
     "Short Title": "MUTADINE - Povidone Iodine Standardised Surgical Scrub Solution 7.5% 4.5 Ltr",
     "Brand Name": "MUTADINE",
     "Manufacturer": "Multicure Pharma Pvt Ltd",
     "Manufacturer Address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Marketer": "Multicure Pharma Pvt Ltd",
     "Marketer address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Description": "Mutadine 7.5% Solution is an antiseptic and disinfectant agent. It is used for the treatment and prevention of infections in wounds and cuts. It kills the harmful microbes and controls their growth, thereby preventing infections in the affected area.\n\nMutadine 7.5% Solution is for external use only. You should always use it exactly as your doctor has told you. The affected area should be clean and dry before application. You must wash your hands thoroughly before and after applying this medicine. This medicine should be used regularly to get the most benefit from it. Do not use more than you need as it will not clear your condition faster and some side effects may be increased. You can help this medication work better by keeping the affected areas clean.",
     "Bullet point 1": "Used in health care as an antiseptic to prep the skin prior to medical procedures, Let it dry for a few minutes",
     "Bullet point 2": "The solution is specially formulated to combat a wide range of harmful microbes, including bacteria and viruses.",
     "Direction to Use": "Used in health care as an antiseptic to prep the skin prior to medical procedures, Let it dry for a few minutes",
     "Safety information": "Avoid contact with eyes and nose. In case of accidental contact, rinse thoroughly with water.\nDo not use it on burnt, broken or inflamed skin.",
     "Ingredients": "Povidone Iodine 7.5 w\/v",
     "OTC\/RX": "OTC",
     "Product Category": "Antiseptic solution",
     "Product Form": "Liquid",
     "Consume Type": "Topical",
     "Unit (s) in Pack": 1,
     "Size": "4.5 Ltr",
     "Stock Quantity": 100,
     "Pack Form\n(Bottle, Tube , Strip etc.)": "HDPE Can",
     "Product Weight In Grams": "4500 G",
     "L in CMs": 18,
     "W in Cms": 13,
     "H in Cms": 27.5,
     "HSN": 30041090,
     "GST %": 12,
     "MRP": 3600,
     "SP": 3333,
     "Discount %": 7.416666666666667,
     "Images Link": "https:\/\/drive.google.com\/drive\/folders\/1QXcv71uCmhJQCzEzZSz8g86R0V54ga7j?usp=drive_link"
    },
    {
     "Sl No": 21,
     "SKU": "MCPPL-PI10-0100",
     "Short Title": "MUTADINE - Povidone Iodine Solution 10% w\/v 100 Ml",
     "Brand Name": "MUTADINE",
     "Manufacturer": "Multicure Pharma Pvt Ltd",
     "Manufacturer Address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Marketer": "Multicure Pharma Pvt Ltd",
     "Marketer address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Description": "Mutadine 10% Solution is an antiseptic and disinfectant agent. It is used for the treatment and prevention of infections in wounds and cuts. It kills the harmful microbes and controls their growth, thereby preventing infections in the affected area.\n\nMutadine 10% Solution is for external use only. You should always use it exactly as your doctor has told you. The affected area should be clean and dry before application. You must wash your hands thoroughly before and after applying this medicine. This medicine should be used regularly to get the most benefit from it. Do not use more than you need as it will not clear your condition faster and some side effects may be increased. You can help this medication work better by keeping the affected areas clean.",
     "Bullet point 1": "Used in health care as an antiseptic to prep the skin prior to medical procedures, Let it dry for a few minutes",
     "Bullet point 2": "The solution is specially formulated to combat a wide range of harmful microbes, including bacteria and viruses.",
     "Direction to Use": "Used in health care as an antiseptic to prep the skin prior to medical procedures, Let it dry for a few minutes",
     "Safety information": "Avoid contact with eyes and nose. In case of accidental contact, rinse thoroughly with water.\nDo not use it on burnt, broken or inflamed skin.",
     "Ingredients": "Povidone Iodine 10% w\/v",
     "OTC\/RX": "OTC",
     "Product Category": "Antiseptic solution",
     "Product Form": "Liquid",
     "Consume Type": "Topical",
     "Unit (s) in Pack": 1,
     "Size": "100 ML",
     "Stock Quantity": 100,
     "Pack Form\n(Bottle, Tube , Strip etc.)": "Bottle",
     "Product Weight In Grams": "100 G",
     "L in CMs": 4.5,
     "W in Cms": 4.5,
     "H in Cms": 10,
     "HSN": 30041090,
     "GST %": 12,
     "MRP": 140,
     "SP": 126,
     "Discount %": 10,
     "Images Link": "https:\/\/drive.google.com\/drive\/folders\/1Pusx14C8on4aohDe96v0d5Bjb77j3mNw?usp=drive_link"
    },
    {
     "Sl No": 22,
     "SKU": "MCPPL-PI10-0500",
     "Short Title": "MUTADINE - Povidone Iodine Solution 10% w\/v 500 ML",
     "Brand Name": "MUTADINE",
     "Manufacturer": "Multicure Pharma Pvt Ltd",
     "Manufacturer Address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Marketer": "Multicure Pharma Pvt Ltd",
     "Marketer address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Description": "Mutadine 10% Solution is an antiseptic and disinfectant agent. It is used for the treatment and prevention of infections in wounds and cuts. It kills the harmful microbes and controls their growth, thereby preventing infections in the affected area.\n\nMutadine 10% Solution is for external use only. You should always use it exactly as your doctor has told you. The affected area should be clean and dry before application. You must wash your hands thoroughly before and after applying this medicine. This medicine should be used regularly to get the most benefit from it. Do not use more than you need as it will not clear your condition faster and some side effects may be increased. You can help this medication work better by keeping the affected areas clean.",
     "Bullet point 1": "Used in health care as an antiseptic to prep the skin prior to medical procedures, Let it dry for a few minutes",
     "Bullet point 2": "The solution is specially formulated to combat a wide range of harmful microbes, including bacteria and viruses.",
     "Direction to Use": "Used in health care as an antiseptic to prep the skin prior to medical procedures, Let it dry for a few minutes",
     "Safety information": "Avoid contact with eyes and nose. In case of accidental contact, rinse thoroughly with water.\nDo not use it on burnt, broken or inflamed skin.",
     "Ingredients": "Povidone Iodine 10% w\/v",
     "OTC\/RX": "OTC",
     "Product Category": "Antiseptic solution",
     "Product Form": "Liquid",
     "Consume Type": "Topical",
     "Unit (s) in Pack": 1,
     "Size": "500 ML",
     "Stock Quantity": 100,
     "Pack Form\n(Bottle, Tube , Strip etc.)": "HDPE Bottle",
     "Product Weight In Grams": "500 G",
     "L in CMs": 6.5,
     "W in Cms": 6.5,
     "H in Cms": 16.5,
     "HSN": 30041090,
     "GST %": 12,
     "MRP": 576,
     "SP": 519,
     "Discount %": 9.895833333333332,
     "Images Link": "https:\/\/drive.google.com\/drive\/folders\/1oPnig69ACrZlsP8eDRP6qBu2xFHNUuWE?usp=drive_link"
    },
    {
     "Sl No": 23,
     "SKU": "MCPPL-PI10-2000",
     "Short Title": "MUTADINE - Povidone Iodine Solution 10% w\/v 2 Ltr",
     "Brand Name": "MUTADINE",
     "Manufacturer": "Multicure Pharma Pvt Ltd",
     "Manufacturer Address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Marketer": "Multicure Pharma Pvt Ltd",
     "Marketer address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Description": "Mutadine 10% Solution is an antiseptic and disinfectant agent. It is used for the treatment and prevention of infections in wounds and cuts. It kills the harmful microbes and controls their growth, thereby preventing infections in the affected area.\n\nMutadine 10% Solution is for external use only. You should always use it exactly as your doctor has told you. The affected area should be clean and dry before application. You must wash your hands thoroughly before and after applying this medicine. This medicine should be used regularly to get the most benefit from it. Do not use more than you need as it will not clear your condition faster and some side effects may be increased. You can help this medication work better by keeping the affected areas clean.",
     "Bullet point 1": "Used in health care as an antiseptic to prep the skin prior to medical procedures, Let it dry for a few minutes",
     "Bullet point 2": "The solution is specially formulated to combat a wide range of harmful microbes, including bacteria and viruses.",
     "Direction to Use": "Used in health care as an antiseptic to prep the skin prior to medical procedures, Let it dry for a few minutes",
     "Safety information": "Avoid contact with eyes and nose. In case of accidental contact, rinse thoroughly with water.\nDo not use it on burnt, broken or inflamed skin.",
     "Ingredients": "Povidone Iodine 10% w\/v",
     "OTC\/RX": "OTC",
     "Product Category": "Antiseptic solution",
     "Product Form": "Liquid",
     "Consume Type": "Topical",
     "Unit (s) in Pack": 1,
     "Size": "2 Ltr",
     "Stock Quantity": 100,
     "Pack Form\n(Bottle, Tube , Strip etc.)": "HDPE Can",
     "Product Weight In Grams": "2000 G",
     "L in CMs": 13,
     "W in Cms": 13,
     "H in Cms": 23,
     "HSN": 30041090,
     "GST %": 12,
     "MRP": 2000,
     "SP": 1800,
     "Discount %": 10,
     "Images Link": "https:\/\/drive.google.com\/drive\/folders\/1_s-MuIR2Q8k5cuUkmZUKYsEz8VU5Oiy5?usp=drive_link"
    },
    {
     "Sl No": 24,
     "SKU": "MCPPL-PI10-4500",
     "Short Title": "MUTADINE - Povidone Iodine Solution 10% w\/v 4.5 Ltr",
     "Brand Name": "MUTADINE",
     "Manufacturer": "Multicure Pharma Pvt Ltd",
     "Manufacturer Address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Marketer": "Multicure Pharma Pvt Ltd",
     "Marketer address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Description": "Mutadine 10% Solution is an antiseptic and disinfectant agent. It is used for the treatment and prevention of infections in wounds and cuts. It kills the harmful microbes and controls their growth, thereby preventing infections in the affected area.\n\nMutadine 10% Solution is for external use only. You should always use it exactly as your doctor has told you. The affected area should be clean and dry before application. You must wash your hands thoroughly before and after applying this medicine. This medicine should be used regularly to get the most benefit from it. Do not use more than you need as it will not clear your condition faster and some side effects may be increased. You can help this medication work better by keeping the affected areas clean.",
     "Bullet point 1": "Used in health care as an antiseptic to prep the skin prior to medical procedures, Let it dry for a few minutes",
     "Bullet point 2": "The solution is specially formulated to combat a wide range of harmful microbes, including bacteria and viruses.",
     "Direction to Use": "Used in health care as an antiseptic to prep the skin prior to medical procedures, Let it dry for a few minutes",
     "Safety information": "Avoid contact with eyes and nose. In case of accidental contact, rinse thoroughly with water.\nDo not use it on burnt, broken or inflamed skin.",
     "Ingredients": "Povidone Iodine 10% w\/v",
     "OTC\/RX": "OTC",
     "Product Category": "Antiseptic solution",
     "Product Form": "Liquid",
     "Consume Type": "Topical",
     "Unit (s) in Pack": 1,
     "Size": "4.5 Ltr",
     "Stock Quantity": 100,
     "Pack Form\n(Bottle, Tube , Strip etc.)": "HDPE Can",
     "Product Weight In Grams": "4500 G",
     "L in CMs": 18,
     "W in Cms": 13,
     "H in Cms": 27.5,
     "HSN": 30041090,
     "GST %": 12,
     "MRP": 4500,
     "SP": 4050,
     "Discount %": 10,
     "Images Link": "https:\/\/drive.google.com\/drive\/folders\/1hw10eVf5r-WN0TEdsYMlTgAQFR5FBHAL?usp=drive_link"
    },
    {
     "Sl No": 25,
     "SKU": "MCPPL-MTLN-1000",
     "Short Title": "MITALON - Antiseptic Disinfectant Liquid 1 Ltr",
     "Brand Name": "MITALON",
     "Manufacturer": "Multicure Pharma Pvt Ltd",
     "Manufacturer Address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Marketer": "Multicure Pharma Pvt Ltd",
     "Marketer address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Description": "Mitalon Antiseptic Disinfectant Liquid is a combination of two medicines used in the treatment of wound infection. It has antimicrobial action on the infections. It kills and inhibits the growth of bacteria thereby preventing abrasions, cuts, or any break in the skin from getting infected.",
     "Direction to Use": "Apply it only on the affected areas of the skin.",
     "Safety information": "Mitalon Antiseptic Disinfectant Liquid is strictly advised for external use only. Use it in the dose and duration advised by your doctor. Apply it only on the affected areas of the skin. In case your eyes or mouth get exposed to this medicine accidentally, wash them thoroughly with water.",
     "Ingredients": "Cetrimide (0.3% v\/v) + Chlorhexidine Gluconate (0.6% w\/v)",
     "OTC\/RX": "OTC",
     "Product Category": "Antiseptic solution",
     "Product Form": "Liquid",
     "Consume Type": "Topical",
     "Unit (s) in Pack": 1,
     "Size": "1 Ltr",
     "Stock Quantity": 100,
     "Pack Form\n(Bottle, Tube , Strip etc.)": "Bottle",
     "Product Weight In Grams": "1000 G",
     "L in CMs": 7,
     "W in Cms": 10,
     "H in Cms": 22.5,
     "HSN": 30041020,
     "GST %": 12,
     "MRP": 235,
     "SP": 212,
     "Discount %": 9.787234042553191,
     "Images Link": "https:\/\/drive.google.com\/drive\/folders\/1Pf0IxLWcBoiuzeUXX7fMfo511igP9BsD?usp=drive_link"
    },
    {
     "Sl No": 26,
     "SKU": "MCPPL-MTLN-0100",
     "Short Title": "MITALON - Antiseptic Disinfectant Liquid 100 ML",
     "Brand Name": "MITALON",
     "Manufacturer": "Multicure Pharma Pvt Ltd",
     "Manufacturer Address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Marketer": "Multicure Pharma Pvt Ltd",
     "Marketer address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Description": "Mitalon Antiseptic Disinfectant Liquid is a combination of two medicines used in the treatment of wound infection. It has antimicrobial action on the infections. It kills and inhibits the growth of bacteria thereby preventing abrasions, cuts, or any break in the skin from getting infected.",
     "Direction to Use": "Apply it only on the affected areas of the skin.",
     "Safety information": "Mitalon Antiseptic Disinfectant Liquid is strictly advised for external use only. Use it in the dose and duration advised by your doctor. Apply it only on the affected areas of the skin. In case your eyes or mouth get exposed to this medicine accidentally, wash them thoroughly with water.",
     "Ingredients": "Cetrimide (0.3% v\/v) + Chlorhexidine Gluconate (0.6% w\/v)",
     "OTC\/RX": "OTC",
     "Product Category": "Antiseptic solution",
     "Product Form": "Liquid",
     "Consume Type": "Topical",
     "Unit (s) in Pack": 1,
     "Size": "100 ML",
     "Stock Quantity": 100,
     "Pack Form\n(Bottle, Tube , Strip etc.)": "Bottle",
     "Product Weight In Grams": "100 G",
     "L in CMs": 3,
     "W in Cms": 5.5,
     "H in Cms": 10.5,
     "HSN": 30041020,
     "GST %": 12,
     "MRP": 85,
     "SP": 79,
     "Discount %": 7.0588235294117645,
     "Images Link": "https:\/\/drive.google.com\/drive\/folders\/1EfGCDNo4qE-ptzDBuYdb1N0nM6w8GhSN?usp=drive_link"
    },
    {
     "Sl No": 27,
     "SKU": "MCPPL-SISO-0100",
     "Short Title": "Doctor Spirit Cetrimide 0.5%, Isopropyl alcohol 70% Anti-Septic Solution 100 ML",
     "Brand Name": "Multicure Pharma",
     "Manufacturer": "Multicure Pharma Pvt Ltd",
     "Manufacturer Address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Marketer": "Multicure Pharma Pvt Ltd",
     "Marketer address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Description": "Doctor Spirit Anti-Septic Solution is a liquid antiseptic solution primarily used as a disinfectant and antiseptic solution for first aid or for cleaning and sanitizing surfaces. The combination of cetrimide and isopropyl alcohol in Multicure Doctor Spirit Anti-Septic Solution may help to prevent infection by killing bacteria, viruses, and fungi that can lead to infections.",
     "Bullet point 1": "Cetrimide is known to have antiseptic properties and can be used to disinfect wounds, while isopropyl alcohol is an effective disinfectant and can help to kill harmful bacteria and viruses",
     "Bullet point 2": "Both cetrimide and isopropyl alcohol can help to clean and sanitize the skin, making them useful for first aid or in a medical setting",
     "Bullet point 3": "Isopropyl alcohol evaporates quickly, making it a convenient ingredient for use in antiseptic solutions that need to dry rapidly",
     "Safety information": "Avoid contact with eyes and nose. In case of accidental contact, rinse thoroughly with water.",
     "Ingredients": "Cetrimide 0.5%, Isopropyl alcohol 70%",
     "OTC\/RX": "OTC",
     "Product Category": "Antiseptic solution",
     "Product Form": "Liquid",
     "Consume Type": "Topical",
     "Unit (s) in Pack": 1,
     "Size": "100 ML",
     "Stock Quantity": 100,
     "Pack Form\n(Bottle, Tube , Strip etc.)": "Bottle",
     "Product Weight In Grams": "100 G",
     "L in CMs": 4.5,
     "W in Cms": 4.5,
     "H in Cms": 10,
     "HSN": 30049099,
     "GST %": 12,
     "MRP": 50,
     "SP": 50,
     "Discount %": 0,
     "Images Link": "https:\/\/drive.google.com\/drive\/folders\/1EyeQ0ucKWPkzr0yMf_RQJTShu1sCyB4A?usp=drive_link"
    },
    {
     "Sl No": 28,
     "SKU": "MCPPL-SISO-0400",
     "Short Title": "Doctor Spirit Cetrimide 0.5%, Isopropyl alcohol 70% Anti-Septic Solution 400 ML",
     "Brand Name": "Multicure Pharma",
     "Manufacturer": "Multicure Pharma Pvt Ltd",
     "Manufacturer Address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Marketer": "Multicure Pharma Pvt Ltd",
     "Marketer address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Description": "Doctor Spirit Anti-Septic Solution is a liquid antiseptic solution primarily used as a disinfectant and antiseptic solution for first aid or for cleaning and sanitizing surfaces. The combination of cetrimide and isopropyl alcohol in Multicure Doctor Spirit Anti-Septic Solution may help to prevent infection by killing bacteria, viruses, and fungi that can lead to infections.",
     "Bullet point 1": "Cetrimide is known to have antiseptic properties and can be used to disinfect wounds, while isopropyl alcohol is an effective disinfectant and can help to kill harmful bacteria and viruses",
     "Bullet point 2": "Both cetrimide and isopropyl alcohol can help to clean and sanitize the skin, making them useful for first aid or in a medical setting",
     "Bullet point 3": "Isopropyl alcohol evaporates quickly, making it a convenient ingredient for use in antiseptic solutions that need to dry rapidly",
     "Safety information": "Avoid contact with eyes and nose. In case of accidental contact, rinse thoroughly with water.",
     "Ingredients": "Cetrimide 0.5%, Isopropyl alcohol 70%",
     "OTC\/RX": "OTC",
     "Product Category": "Antiseptic solution",
     "Product Form": "Liquid",
     "Consume Type": "Topical",
     "Unit (s) in Pack": 1,
     "Size": "400 ML",
     "Stock Quantity": 100,
     "Pack Form\n(Bottle, Tube , Strip etc.)": "Bottle",
     "Product Weight In Grams": "400 G",
     "L in CMs": 6.5,
     "W in Cms": 6.5,
     "H in Cms": 17,
     "HSN": 30049099,
     "GST %": 12,
     "MRP": 230,
     "SP": 207,
     "Discount %": 10,
     "Images Link": "https:\/\/drive.google.com\/open?id=1E9Lqbjlsydm0jv81-_7QKKK86kNKtqSp&usp=drive_copy"
    },
    {
     "Sl No": 29,
     "SKU": "MCPPL-MHPB-0450",
     "Short Title": "Mitanyle Hospital & Doctor's Choice Black grade 3A Phenyl 450 ML",
     "Brand Name": "Mitanyle",
     "Manufacturer": "Multicure Pharma Pvt Ltd",
     "Manufacturer Address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Marketer": "Multicure Pharma Pvt Ltd",
     "Marketer address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Description": "Mitanyle is very good at removing many kinds of bacteria. It is a powerful disinfectant with a long shelf life that may be used in homes, hospitals, government organizations, schools, offices, and manufacturing units for general cleaning of toilets, drains, floors, etc. It has a strong fragrance that lasts for a number of hours and is quite effective when there is a lot of organic pollution.",
     "Bullet point 1": "Kills bacteria, viruses, and fungi.",
     "Bullet point 2": "Suitable for hospitals, government organizations, schools, offices, and manufacturing units",
     "Bullet point 3": "Used for general cleaning of toilets, drains, floors etc",
     "Bullet point 4": "It has a strong fragrance that lasts for a number of hours",
     "Safety information": "Store in a cool and dry place, away from sunlight.\nKeep out of reach of children",
     "Ingredients": "Black grade 3A Phenyl",
     "OTC\/RX": "OTC",
     "Product Category": "Disinfectant liquid",
     "Product Form": "Liquid",
     "Unit (s) in Pack": 1,
     "Size": "450 Ml",
     "Stock Quantity": 100,
     "Pack Form\n(Bottle, Tube , Strip etc.)": "Bottle",
     "Product Weight In Grams": "450 G",
     "L in CMs": 7,
     "W in Cms": 7,
     "H in Cms": 18,
     "HSN": 38089400,
     "GST %": 18,
     "MRP": 110,
     "SP": 110,
     "Discount %": 0,
     "Images Link": "https:\/\/drive.google.com\/drive\/folders\/1gKeurJmIJ1IWkLRQAvc-QSO0hq3TmwoD?usp=sharing"
    },
    {
     "Sl No": 30,
     "SKU": "MCPPL-MHPB-1000",
     "Short Title": "Mitanyle Hospital & Doctor's Choice Black grade 3A Phenyl 1 Ltr",
     "Brand Name": "Mitanyle",
     "Manufacturer": "Multicure Pharma Pvt Ltd",
     "Manufacturer Address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Marketer": "Multicure Pharma Pvt Ltd",
     "Marketer address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Description": "Mitanyle is very good at removing many kinds of bacteria. It is a powerful disinfectant with a long shelf life that may be used in homes, hospitals, government organizations, schools, offices, and manufacturing units for general cleaning of toilets, drains, floors, etc. It has a strong fragrance that lasts for a number of hours and is quite effective when there is a lot of organic pollution.",
     "Bullet point 1": "Kills bacteria, viruses, and fungi.",
     "Bullet point 2": "Suitable for hospitals, government organizations, schools, offices, and manufacturing units",
     "Bullet point 3": "Used for general cleaning of toilets, drains, floors etc",
     "Bullet point 4": "It has a strong fragrance that lasts for a number of hours",
     "Safety information": "Store in a cool and dry place, away from sunlight.\nKeep out of reach of children",
     "Ingredients": "Black grade 3A Phenyl",
     "OTC\/RX": "OTC",
     "Product Category": "Disinfectant liquid",
     "Product Form": "Liquid",
     "Unit (s) in Pack": 1,
     "Size": "1 Ltr",
     "Stock Quantity": 100,
     "Pack Form\n(Bottle, Tube , Strip etc.)": "Bottle",
     "Product Weight In Grams": "1000 G",
     "L in CMs": 8,
     "W in Cms": 8,
     "H in Cms": 23.5,
     "HSN": 38089400,
     "GST %": 18,
     "MRP": 200,
     "SP": 190,
     "Discount %": 5,
     "Images Link": "https:\/\/drive.google.com\/drive\/folders\/1cb7IxNTj5K9HcOhIFSmuE0USX2A4cRBP?usp=sharing"
    },
    {
     "Sl No": 31,
     "SKU": "MCPPL-MHPB-4500",
     "Short Title": "Mitanyle Hospital & Doctor's Choice Black grade 3A Phenyl 4.5 Ltr",
     "Brand Name": "Mitanyle",
     "Manufacturer": "Multicure Pharma Pvt Ltd",
     "Manufacturer Address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Marketer": "Multicure Pharma Pvt Ltd",
     "Marketer address": "14A, IDA, Yadadri Bhuvanagiri, Bhongir, Telangana, 508116",
     "Description": "Mitanyle is very good at removing many kinds of bacteria. It is a powerful disinfectant with a long shelf life that may be used in homes, hospitals, government organizations, schools, offices, and manufacturing units for general cleaning of toilets, drains, floors, etc. It has a strong fragrance that lasts for a number of hours and is quite effective when there is a lot of organic pollution.",
     "Bullet point 1": "Kills bacteria, viruses, and fungi.",
     "Bullet point 2": "Suitable for hospitals, government organizations, schools, offices, and manufacturing units",
     "Bullet point 3": "Used for general cleaning of toilets, drains, floors etc",
     "Bullet point 4": "It has a strong fragrance that lasts for a number of hours",
     "Safety information": "Store in a cool and dry place, away from sunlight.\nKeep out of reach of children",
     "Ingredients": "Black grade 3A Phenyl",
     "OTC\/RX": "OTC",
     "Product Category": "Disinfectant liquid",
     "Product Form": "Liquid",
     "Unit (s) in Pack": 1,
     "Size": "4.5 Ltr",
     "Stock Quantity": 100,
     "Pack Form\n(Bottle, Tube , Strip etc.)": "HDPE Can",
     "Product Weight In Grams": "4500 G",
     "L in CMs": 23.5,
     "W in Cms": 12.5,
     "H in Cms": 25,
     "HSN": 38089400,
     "GST %": 18,
     "MRP": 850,
     "SP": 765,
     "Discount %": 10,
     "Images Link": "https:\/\/drive.google.com\/drive\/folders\/1CXOGbwa4WekECoczUTl84PRk-3TBeKEM?usp=sharing"
    }
   ]
  
  export default products;
  